export const CREATE_SEAT_LAYOUT_REQUEST = "CREATE_SEAT_LAYOUT_REQUEST";
export const CREATE_SEAT_LAYOUT_SUCCESS = "CREATE_SEAT_LAYOUT_SUCCESS";
export const CREATE_SEAT_LAYOUT_FAILURE = "CREATE_SEAT_LAYOUT_FAILURE";
