export const GET_SEAT_LAYOUT_BY_MSC_REQUEST = "GET_SEAT_LAYOUT_BY_MSC_REQUEST";
export const GET_SEAT_LAYOUT_BY_MSC_SUCCESS = "GET_SEAT_LAYOUT_BY_MSC_SUCCESS";
export const GET_SEAT_LAYOUT_BY_MSC_FAILURE = "GET_SEAT_LAYOUT_BY_MSC_FAILURE";
