export const GET_ALL_CAROUSELS_REQUEST = "GET_ALL_CAROUSELS_REQUEST";
export const GET_ALL_CAROUSELS_SUCCESS = "GET_ALL_CAROUSELS_SUCCESS";
export const GET_ALL_CAROUSELS_FAILURE = "GET_ALL_CAROUSELS_FAILURE";
