export const CREATE_NEW_COMMENT_REQUEST = "CREATE_NEW_COMMENT_REQUEST";
export const CREATE_NEW_COMMENT_SUCCESS = "CREATE_NEW_COMMENT_SUCCESS";
export const CREATE_NEW_COMMENT_FAILURE = "CREATE_NEW_COMMENT_FAILURE";
