export const GET_ALL_COMMENTS_BY_MA_PHIM_REQUEST =
  "GET_ALL_COMMENTS_BY_MA_PHIM_REQUEST";
export const GET_ALL_COMMENTS_BY_MA_PHIM_SUCCESS =
  "GET_ALL_COMMENTS_BY_MA_PHIM_SUCCESS";
export const GET_ALL_COMMENTS_BY_MA_PHIM_FAILURE =
  "GET_ALL_COMMENTS_BY_MA_PHIM_FAILURE";
