export const GET_ALL_CUM_RAPS_REQUEST = "GET_ALL_CUM_RAPS_REQUEST";
export const GET_ALL_CUM_RAPS_SUCCESS = "GET_ALL_CUM_RAPS_SUCCESS";
export const GET_ALL_CUM_RAPS_FAILURE = "GET_ALL_CUM_RAPS_FAILURE";
