export const GET_ALL_THEATERS_REQUEST = "GET_ALL_THEATERS_REQUEST";
export const GET_ALL_THEATERS_SUCCESS = "GET_ALL_THEATERS_SUCCESS";
export const GET_ALL_THEATERS_FAILURE = "GET_ALL_THEATERS_FAILURE";
