export const GET_MOVIES_BY_THEATER_REQUEST = "GET_MOVIES_BY_THEATER_REQUEST";
export const GET_MOVIES_BY_THEATER_SUCCESS = "GET_MOVIES_BY_THEATER_SUCCESS";
export const GET_MOVIES_BY_THEATER_FAILURE = "GET_MOVIES_BY_THEATER_FAILURE";
